attrs:
  title: pilot_radiosonde
  description: To be updated 
  location_id: cali #To be updated 
  dataset_name: pilot_radiosonde
  data_level: a1

coords:
  time:
    dims: [time]
    dtype: datetime64[s]
    attrs:
      units: Seconds since 1970-01-01 00:00:00

data_vars:
  air_temperature:
    dims: [time]
    dtype: float
    attrs:
      standard_name: air_temperature
      units: degC
  dew_point_temperature:
    dims: [time]
    dtype: float
    attrs:
      standard_name: dew_point_temperature
      units: K
  air_pressure:
    dims: [time]
    dtype: float
    attrs:
      long_name: Surface Air Pressure in mbar from a sensor on the lidar
      units: hPa
  relative_humidity:
    dims: [time]
    dtype: float
    attrs:
      long_name: Relative Humidity
      units: "%"
  wind_speed:
    dims: [time]
    dtype: float
    attrs:
      description: "average wind speed (horizontal)"
      units: m/s
  wind_direction:
    dims: [time]
    dtype: float
    attrs:
      long_name: Wind Direction
      units: degrees
  eastward_wind:
    dims: [time]
    dtype: float
    attrs:
      standard_name: eastward_wind
      units: m/s
  northward_wind:
    dims: [time]
    dtype: float
    attrs:
      standard_name: northward_wind
      units: m/s

  latitude:
      dims: [time]
      dtype: float
      attrs:
        long_name: "North latitude"
        standard_name: "latitude"
        description: "Recorded lattitude at the instrument location"
        units: degree_N
  longitude:
    dims: [time]
    dtype: float
    attrs:
      long_name: "East longitude"
      standard_name: "longitude"
      description: "Recorded longitude at the instrument location"
      units: degree_E
  altitude:
    dims: [time]
    dtype: float
    attrs:
      long_name: "Altitude"
      standard_name: "altitude"
      description: "Recorded altitude at the instrument location"
      units: m
