attrs:
  title: SMODE_iop1_Radiosonde
  description: S-Mode field campaign Radiosonde observations during Pilot campaign.
  location_id: smode 
  dataset_name: sonde
  z_id: ship
  data_level: a1
  qualifier: pilot

coords:
  time:
    dims: [time]
    dtype: datetime64[ns]
    attrs:
      long_name: UTC time
      standard_name: time
      units: Seconds since 1970-01-01 00:00:00 UTC

data_vars:
  id:
    dims: []
    dtype: float
    attrs: 
      units: "1"
  air_temperature:
    dims: [time]
    dtype: float
    attrs:
      standard_name: air_temperature
      long_name: Air Temperature
      units: degC
  dew_point_temperature:
    dims: [time]
    dtype: float
    attrs:
      standard_name: dew_point_temperature
      long_name: Dew Point Temperature
      units: degC
  air_pressure:
    dims: [time]
    dtype: float
    attrs:
      standard_name: air_pressure
      long_name: Air Pressure
      units: hPa
  relative_humidity:
    dims: [time]
    dtype: float
    attrs:
      standard_name: relative_humidity
      long_name: Relative Humidity
      units: "%"
  wind_speed:
    dims: [time]
    dtype: float
    attrs:
      standard_name: wind_speed
      long_name: Wind Speed
      units: m/s
  wind_direction:
    dims: [time]
    dtype: float
    attrs:
      standard_name: wind_from_direction
      long_name: Wind Direction 
      units: degrees
  eastward_wind:
    dims: [time]
    dtype: float
    attrs:
      standard_name: eastward_wind
      long_name: Eastward Wind Component
      units: m/s
  northward_wind:
    dims: [time]
    dtype: float
    attrs:
      standard_name: northward_wind
      long_name: Northward Wind Component
      units: m/s

  latitude:
      dims: [time]
      dtype: float
      attrs:
        long_name: North latitude
        standard_name: latitude
        comment: Recorded latitude at the instrument location
        units: degree_N
  longitude:
    dims: [time]
    dtype: float
    attrs:
      long_name: East longitude
      standard_name: longitude
      comment: Recorded longitude at the instrument location
      units: degree_E
  altitude:
    dims: [time]
    dtype: float
    attrs:
      long_name: Altitude
      standard_name: altitude
      comment: Recorded altitude at the instrument location
      units: m
