classname: pipelines.noaa_cns_temp.pipeline.NoaaCnsTemp

triggers:
  - .*/noaa_cns_temp/test/data/input/nps/.*/.*/nps.*t

retriever:
  path: pipelines/noaa_cns_temp/config/retriever.yaml

dataset:
  path: pipelines/noaa_cns_temp/config/dataset.yaml

quality:
  path: shared/quality.yaml
storage:
  path: shared/storage.yaml