classname: tsdat.io.retrievers.DefaultRetriever
readers:
  .*:
    classname: pipelines.smode_iop1_saildrone.readers.pilot_saildrone

coords:
  time:
    name: time

data_vars:
  trajectory:
    name: trajectory
  longitude:
    name: longitude
  latitude:
    name: latitude
  SOG:
    name: SOG
  SOG_FILTERED_MEAN:
    name: SOG_FILTERED_MEAN
  SOG_FILTERED_STDDEV:
    name: SOG_FILTERED_STDDEV
  SOG_FILTERED_MAX:
    name: SOG_FILTERED_MAX
  SOG_FILTERED_MIN:
    name: SOG_FILTERED_MIN 
  COG:
    name: COG
  COG_FILTERED_MEAN:
    name: COG_FILTERED_MEAN
  COG_FILTERED_STDDEV:
    name: COG_FILTERED_STDDEV
  HDG:
    name: HDG
  HDG_FILTERED_MEAN:
    name: HDG_FILTERED_MEAN 
  HDG_FILTERED_STDDEV:
    name: HDG_FILTERED_STDDEV 
  ROLL_FILTERED_MEAN:
    name: ROLL_FILTERED_MEAN
  ROLL_FILTERED_STDDEV:
    name: ROLL_FILTERED_STDDEV
  ROLL_FILTERED_PEAK:
    name: ROLL_FILTERED_PEAK
  PITCH_FILTERED_MEAN:
    name: PITCH_FILTERED_MEAN
  PITCH_FILTERED_STDDEV:
    name: PITCH_FILTERED_STDDEV
  PITCH_FILTERED_PEAK:
    name: PITCH_FILTERED_PEAK
  HDG_WING:
    name: HDG_WING 
  WING_HDG_FILTERED_MEAN:
    name: WING_HDG_FILTERED_MEAN
  WING_HDG_FILTERED_STDDEV:
    name: WING_HDG_FILTERED_STDDEV
  WING_ROLL_FILTERED_MEAN:
    name: WING_ROLL_FILTERED_MEAN
  WING_ROLL_FILTERED_STDDEV:
    name: WING_ROLL_FILTERED_STDDEV
  WING_ROLL_FILTERED_PEAK:
    name: WING_ROLL_FILTERED_PEAK 
  WING_PITCH_FILTERED_MEAN:
    name: WING_PITCH_FILTERED_MEAN
  WING_PITCH_FILTERED_STDDEV:
    name: WING_PITCH_FILTERED_STDDEV
  WING_PITCH_FILTERED_PEAK:
    name: WING_PITCH_FILTERED_PEAK
  WING_ANGLE:
    name: WING_ANGLE
  WIND_FROM_MEAN:
    name: WIND_FROM_MEAN
  WIND_FROM_STDDEV:
    name: WIND_FROM_STDDEV
  WIND_SPEED_MEAN:
    name: WIND_SPEED_MEAN
  WIND_SPEED_STDDEV:
    name: WIND_SPEED_STDDEV
  UWND_MEAN:
    name: UWND_MEAN
  UWND_STDDEV:
    name: UWND_STDDEV
  VWND_MEAN:
    name: VWND_MEAN
  VWND_STDDEV:
    name: VWND_STDDEV
  WWND_MEAN:
    name: WWND_MEAN
  WWND_STDDEV:
    name: WWND_STDDEV
  GUST_WND_MEAN:
    name: GUST_WND_MEAN
  GUST_WND_STDDEV:
    name: GUST_WND_STDDEV
  WIND_MEASUREMENT_HEIGHT_MEAN:
    name: WIND_MEASUREMENT_HEIGHT_MEAN
  WIND_MEASUREMENT_HEIGHT_STDDEV:
    name: WIND_MEASUREMENT_HEIGHT_STDDEV
  TEMP_AIR_MEAN:
    name: TEMP_AIR_MEAN
  TEMP_AIR_STDDEV:
    name: TEMP_AIR_STDDEV
  RH_MEAN:
    name: RH_MEAN
  RH_STDDEV:
    name: RH_STDDEV
  BARO_PRES_MEAN:
    name: BARO_PRES_MEAN
  BARO_PRES_STDDEV:
    name: BARO_PRES_STDDEV
  PAR_AIR_MEAN:
    name: PAR_AIR_MEAN
  PAR_AIR_STDDEV:
    name: PAR_AIR_STDDEV
  TEMP_IR_SEA_WING_UNCOMP_MEAN:
    name: TEMP_IR_SEA_WING_UNCOMP_MEAN
  TEMP_IR_SEA_WING_UNCOMP_STDDEV:
    name: TEMP_IR_SEA_WING_UNCOMP_STDDEV
  WAVE_DOMINANT_PERIOD:
    name: WAVE_DOMINANT_PERIOD
  WAVE_SIGNIFICANT_HEIGHT:
    name: WAVE_SIGNIFICANT_HEIGHT
  TEMP_SBE37_MEAN:
    name: TEMP_SBE37_MEAN
  TEMP_SBE37_STDDEV:
    name: TEMP_SBE37_STDDEV
  SAL_SBE37_MEAN:
    name: SAL_SBE37_MEAN
  SAL_SBE37_STDDEV:
    name: SAL_SBE37_STDDEV
  COND_SBE37_MEAN:
    name: COND_SBE37_MEAN
  COND_SBE37_STDDEV:
    name: COND_SBE37_STDDEV
  O2_CONC_SBE37_MEAN:
    name: O2_CONC_SBE37_MEAN
  O2_CONC_SBE37_STDDEV:
    name: O2_CONC_SBE37_STDDEV
  O2_SAT_SBE37_MEAN:
    name: O2_SAT_SBE37_MEAN
  O2_SAT_SBE37_STDDEV:
    name: O2_SAT_SBE37_STDDEV
  CHLOR_WETLABS_MEAN:
    name: CHLOR_WETLABS_MEAN
  CHLOR_WETLABS_STDDEV:
    name: CHLOR_WETLABS_STDDEV
  CDOM_MEAN:
    name: CDOM_MEAN
  CDOM_STDDEV:
    name: CDOM_STDDEV
  BKSCT_RED_MEAN:
    name: BKSCT_RED_MEAN
  BKSCT_RED_STDDEV:
    name: BKSCT_RED_STDDEV
  WATER_CURRENT_SPEED_MEAN:
    name: WATER_CURRENT_SPEED_MEAN
  WATER_CURRENT_DIRECTION_MEAN:
    name: WATER_CURRENT_DIRECTION_MEAN