# DEVELOPER: Add attrs and coords/variables to specify the output data structure

attrs:
  title: NDBC
  description: Data from National Data Buoy Center in California
  location_id: california
  dataset_name: buoy_46011
  data_level: b0

coords:
  time:
    dims: [time]
    dtype: datetime64[s]
    attrs:
      long_name: Time (UTC)
      units: Seconds since 1970-01-01 00:00:00

data_vars:
  wind_direction:
    dims: [time]
    dtype: float32
    attrs:
      long_name: wind direction
      standard_name: wind_from_direction
      units: degT
      #_FillValue: -9999

  wind_speed:
    dims: [time]
    dtype: float32
    attrs:
      long_name: wind speed
      standard_name: wind_speed
      units: m/s
      #_FillValue: -9999

  peak_gust_speed:
    dims: [time]
    dtype: float32
    attrs:
      long_name: Peak gust speed
      standard_name: wind_speed_of_gust
      units: m/s
      #_FillValue: -9999

  significant_wave_height:
    dims: [time]
    dtype: float32
    attrs:
      long_name: Significant wave height
      standard_name: sea_surface_wave_significant_height
      units: m
      #_FillValue: -9999

  dominant_wave_period:
    dims: [time]
    dtype: float32
    attrs:
      long_name: Dominant wave period
      standard_name: sea_surface_wave_period_at_variance_spectral_density_maximum
      units: s
      #_FillValue: -9999

  average_wave_period:
    dims: [time]
    dtype: float32
    attrs:
      long_name: Average wave period
      standard_name: sea_surface_wave_mean_period_from_variance_spectral_density_first_frequency_moment
      units: s
      #_FillValue: -9999

  dominant_wave_direction:
    dims: [time]
    dtype: float32
    attrs:
      long_name:
        The direction from which the waves at the dominant period (DPD) are coming
      standard_name: sea_surface_wave_from_direction
      units: degT
      #_FillValue: -9999

  sea_level_pressure:
    dims: [time]
    dtype: float32
    attrs:
      long_name: Sea level pressure
      standard_name: air_pressure_at_mean_sea_level
      units: hPa
      #_FillValue: -9999

  air_temperature:
    dims: [time]
    dtype: float32
    attrs:
      long_name: Air temperature
      standard_name: air_temperature
      units: degC
      #_FillValue: -9999

  sea_surface_temperature:
    dims: [time]
    dtype: float32
    attrs:
      long_name: Sea surface temperature
      standard_name: sea_surface_temperature
      units: degC
      #_FillValue: -9999

  dewpoint_temperature:
    dims: [time]
    dtype: float32
    attrs:
      long_name: Dewpoint temperature
      standard_name: dew_point_temperature
      units: degC
      #_FillValue: -9999

  visibility:
    dims: [time]
    dtype: float32
    attrs:
      long_name: Station visibility
      standard_name: visibility_in_air
      units: m
      #_FillValue: -9999

  tide:
    dims: [time]
    dtype: float32
    attrs:
      long_name: Water level
      standard_name: tidal_sea_surface_height_above_mean_lower_low_water
      units: m
      #_FillValue: -9999

  latitude:
    data: 34.936
    dims: []
    dtype: float32
    attrs:
      long_name: North latitude
      standard_name: latitude
      comment: Recorded lattitude at the instrument location
      units: degN
      #_FillValue: -9999

  longitude:
    data: -120.998
    dims: []
    dtype: float32
    attrs:
      long_name: East longitude
      standard_name: longitude
      comment: Recorded longitude at the instrument location
      units: degE
      #_FillValue: -9999

  site_elevation:
    data: 0
    dims: []
    dtype: float32
    attrs:
      units: m
      #_FillValue: -9999

  air_temp_height:
    data: 3.4
    dims: []
    dtype: float32
    attrs:
      units: m
      long_name: Air temperature height
      comment: above sea level
      #_FillValue: -9999

  anemometer_height:
    data: 3.8
    dims: []
    dtype: float32
    attrs:
      units: m
      comment: above sea level
      #_FillValue: -9999

  barometer_elevation:
    data: 2.4
    dims: []
    dtype: float32
    attrs:
      units: m
      comment: above mean sea level
      #_FillValue: -9999

  sea_temp_depth:
    data: 2
    dims: []
    dtype: float32
    attrs:
      units: m
      long_name: sea temperature depth
      comment: below water line
      #_FillValue: -9999

  water_depth:
    data: 419
    dims: []
    dtype: float32
    attrs:
      units: m
      #_FillValue: -9999

  watch_circle_radius:
    data: 738
    dims: []
    dtype: float32
    attrs:
      units: yards
      #_FillValue: -9999
