# DEVELOPER: Add attrs and coords/variables to specify the output data structure

attrs:
  title: NDBC
  description: Data from National Data Buoy Center in California
  location_id: 46011
  dataset_name: buoy_z01
  instance: z01
  data_level: b0

coords:
  time:
    dims: [time]
    dtype: datetime64[s]
    attrs:
      long_name: Time
      standard_name: time
      units: Seconds since 1970-01-01 00:00:00 UTC
      timezone: UTC

data_vars:
  wind_direction:
    dims: [time]
    dtype: float32
    attrs:
      long_name: Wind direction
      standard_name: wind_from_direction
      units: degrees

  wind_speed:
    dims: [time]
    dtype: float32
    attrs:
      long_name: Wind speed
      standard_name: wind_speed
      units: m/s

  peak_gust_speed:
    dims: [time]
    dtype: float32
    attrs:
      long_name: Peak gust speed
      standard_name: wind_speed_of_gust
      units: m/s

  significant_wave_height:
    dims: [time]
    dtype: float32
    attrs:
      long_name: Significant wave height
      standard_name: sea_surface_wave_significant_height
      units: m

  dominant_wave_period:
    dims: [time]
    dtype: float32
    attrs:
      long_name: Dominant wave period
      standard_name: sea_surface_wave_period_at_variance_spectral_density_maximum
      units: s

  average_wave_period:
    dims: [time]
    dtype: float32
    attrs:
      long_name: Average wave period
      standard_name: sea_surface_wave_mean_period_from_variance_spectral_density_first_frequency_moment
      units: s

  dominant_wave_direction:
    dims: [time]
    dtype: float32
    attrs:
      long_name: Dominant Wave Direction
      standard_name: sea_surface_wave_from_direction
      comment:
        the direction from which the waves at the dominant period (DPD) are coming
      units: degrees

  sea_level_pressure:
    dims: [time]
    dtype: float32
    attrs:
      long_name: Sea Level Pressure
      standard_name: air_pressure_at_mean_sea_level
      units: hPa

  air_temperature:
    dims: [time]
    dtype: float32
    attrs:
      long_name: Air Temperature
      standard_name: air_temperature
      units: degC

  sea_surface_temperature:
    dims: [time]
    dtype: float32
    attrs:
      long_name: Sea Surface Temperature
      standard_name: sea_surface_temperature
      units: degC

  dewpoint_temperature:
    dims: [time]
    dtype: float32
    attrs:
      long_name: Dewpoint Temperature
      standard_name: dew_point_temperature
      units: degC

  visibility:
    dims: [time]
    dtype: float32
    attrs:
      long_name: Station Visibility
      standard_name: visibility_in_air
      units: m

  tide:
    dims: [time]
    dtype: float32
    attrs:
      long_name: Water Level
      standard_name: tidal_sea_surface_height_above_mean_lower_low_water
      units: m

  latitude:
    data: 34.936
    dims: []
    dtype: float32
    attrs:
      long_name: Latitude
      standard_name: latitude
      comment: Recorded latitude at the instrument location
      units: degree_N

  longitude:
    data: -120.998
    dims: []
    dtype: float32
    attrs:
      long_name: Longitude
      standard_name: longitude
      comment: Recorded longitude at the instrument location
      units: degree_E

  site_elevation:
    data: 0
    dims: []
    dtype: float32
    attrs:
      long_name: Site Elevation
      units: m

  air_temp_height:
    data: 3.4
    dims: []
    dtype: float32
    attrs:
      units: m
      long_name: Air Temperature Height
      comment: above sea level

  anemometer_height:
    data: 3.8
    dims: []
    dtype: float32
    attrs:
      units: m
      long_name: Anemometer Height
      comment: above MSL

  barometer_elevation:
    data: 2.4
    dims: []
    dtype: float32
    attrs:
      units: m
      long_name: Barometer Elevation
      comment: above MSL

  sea_temp_depth:
    data: 2
    dims: []
    dtype: float32
    attrs:
      units: m
      long_name: Sea Temperature Depth
      comment: below water line

  water_depth:
    data: 419
    dims: []
    dtype: float32
    attrs:
      long_name: Water Depth
      units: m

  watch_circle_radius:
    data: 674.827
    dims: []
    dtype: float32
    attrs:
      long_name: Watch Circle Radius
      units: m
