# DEVELOPER: Add attrs and coords/variables to specify the output data structure

attrs:
  title: NDBC
  description: Data from Station 46011 of the coast of Point Arguello, CA
  location_id: california
  dataset_name: buoy_46011
  data_level: b0

coords:
  time:
    dims: [time]
    dtype: datetime64[s]
    attrs:
      long_name: Time (UTC)
      units: Seconds since 1970-01-01 00:00:00

data_vars:
  WD:
    dims: [time]
    dtype: float
    attrs:
      long_name: Wind direction
      units: degT
      _FillValue: -9999

  WDIR:
    dims: [time]
    dtype: float
    attrs:
      long_name: Wind direction
      units: degT
      _FillValue: -9999

  WSPD:
    dims: [time]
    dtype: float
    attrs:
      long_name: Wind speed
      units: m/s
      _FillValue: -9999

  GST:
    dims: [time]
    dtype: float
    attrs:
      long_name: Peak gust speed
      units: m/s
      _FillValue: -9999

  WVHT:
    dims: [time]
    dtype: float
    attrs:
      long_name: Significant wave height
      units: m
      _FillValue: -9999

  DPD:
    dims: [time]
    dtype: float
    attrs:
      long_name: Dominant wave period
      units: sec
      _FillValue: -9999

  APD:
    dims: [time]
    dtype: float
    attrs:
      long_name: Average wave period
      units: sec
      _FillValue: -9999

  MWD:
    dims: [time]
    dtype: float
    attrs:
      long_name:
        The direction from which the waves at the dominant period (DPD) are coming
      units: degT
      _FillValue: -9999

  BAR:
    dims: [time]
    dtype: float
    attrs:
      long_name: Sea level pressure
      units: hPa
      _FillValue: -9999

  PRES:
    dims: [time]
    dtype: float
    attrs:
      long_name: Sea level pressure
      units: hPa
      _FillValue: -9999

  ATMP:
    dims: [time]
    dtype: float
    attrs:
      long_name: Air temperature
      units: degC
      _FillValue: -9999

  WTMP:
    dims: [time]
    dtype: float
    attrs:
      long_name: Sea surface temperature
      units: degC
      _FillValue: -9999

  DEWP:
    dims: [time]
    dtype: float
    attrs:
      long_name: Dewpoint temperature
      units: nmi
      _FillValue: -9999

  VIS:
    dims: [time]
    dtype: float
    attrs:
      long_name: Station visibility
      units: hPa
      _FillValue: -9999

  TIDE:
    dims: [time]
    dtype: float
    attrs:
      long_name: Water level
      units: ft
      _FillValue: -9999

  latitude:
    data: 34.936
    dims: []
    dtype: float
    attrs:
      long_name: North latitude
      standard_name: latitude
      comment: Recorded lattitude at the instrument location
      units: degN
      _FillValue: -9999

  longitude:
    data: 120.998
    dims: []
    dtype: float
    attrs:
      long_name: East longitude
      standard_name: longitude
      comment: Recorded longitude at the instrument location
      units: degE
      _FillValue: -9999

  Site_elevation:
    data: 0
    dims: []
    dtype: float
    attrs:
      units: m
      _FillValue: -9999

  Air_temp_height:
    data: 3.4
    dims: []
    dtype: float
    attrs:
      units: m
      long_name: Air temperature height
      comment: above sea level
      _FillValue: -9999

  Anemometer_height:
    data: 3.8
    dims: []
    dtype: float
    attrs:
      units: m
      comment: above sea level
      _FillValue: -9999

  Barometer_elevation:
    data: 2.4
    dims: []
    dtype: float
    attrs:
      units: m
      comment: above mean sea level
      _FillValue: -9999

  Sea_temp_depth:
    data: 2
    dims: []
    dtype: float
    attrs:
      units: m
      long_name: sea temperature depth
      comment: below water line
      _FillValue: -9999

  Water_depth:
    data: 419
    dims: []
    dtype: float
    attrs:
      units: m
      _FillValue: -9999

  Watch_circle_radius:
    data: 738
    dims: []
    dtype: float
    attrs:
      units: yards
      _FillValue: -9999
