classname: pipelines.ndbc.pipeline.Ndbc

triggers:
  - .*46042.*.txt

retriever:
  path: pipelines/ndbc/config/retriever.yaml

dataset:
  path: pipelines/ndbc/config/dataset.yaml
  overrides:
    /attrs/dataset_name: buoy_46042
    /data_vars/latitude/data: 36.785
    /data_vars/longitude/data: -122.396
    /data_vars/site_elevation/data: 0
    /data_vars/air_temp_height/data: 3.4
    /data_vars/anemometer_height/data: 3.8
    /data_vars/barometer_elevation/data: 2.4
    /data_vars/sea_temp_depth/data: 2
    /data_vars/water_depth/data: 1693
    /data_vars/watch_circle_radius/data: 1793

quality:
  path: shared/quality.yaml
storage:
  path: shared/storage.yaml
