classname: pipelines.ndbc.pipeline.Ndbc

triggers:
  - .*46026.*.txt

retriever:
  path: pipelines/ndbc/config/retriever.yaml

dataset:
  path: pipelines/ndbc/config/dataset.yaml
  overrides:
    /attrs/location_id: 46026
    /data_vars/latitude/data: 37.754
    /data_vars/longitude/data: -122.839
    /data_vars/site_elevation/data: 0
    /data_vars/air_temp_height/data: 3.4
    /data_vars/anemometer_height/data: 3.8
    /data_vars/barometer_elevation/data: 2.4
    /data_vars/sea_temp_depth/data: 2
    /data_vars/water_depth/data: 54.9
    /data_vars/watch_circle_radius/data: 90.5256

quality:
  path: shared/quality.yaml
storage:
  path: shared/storage.yaml
