classname: tsdat.io.retrievers.DefaultRetriever
readers:
  .*:
    classname: pipelines.ndbc.readers.CustomDataReader

coords:
  time:
    data_converters:
      - classname: tsdat.io.converters.StringToDatetime
        format: "%Y-%m-%d %H:%M:%S"
        timezone: UTC
    name: time

data_vars:
  wind_direction:
    name: [WD, WDIR]

  wind_speed:
    name: WSPD

  peak_gust_speed:
    name: GST

  significant_wave_height:
    name: WVHT

  dominant_wave_period:
    name: DPD

  average_wave_period:
    name: APD

  dominant_wave_direction:
    name: MWD

  sea_level_pressure:
    name: [BAR, PRES]

  air_temperature:
    name: ATMP

  sea_surface_temperature:
    name: WTMP

  dewpoint_temperature:
    name: DEWP

  visibility:
    name: VIS
    data_converters:
      - classname: tsdat.io.converters.UnitsConverter
        input_units: nmi

  tide:
    name: TIDE
    data_converters:
      - classname: tsdat.io.converters.UnitsConverter
        input_units: ft

  #latitude:
  #  name: latitude

  #longitude:
  #  name: longitude

  #site_elevation:
  #  name: site_elevation

  #air_temp_height:
  #  name: air_temp_height

  #anemometer_height:
  #  name: anemometer_height

  #barometer_elevation:
  #  name: barometer_elevation

  #sea_temp_depth:
  #  name: sea_temp_depth

  #water_depth:
  #  name: water_depth

  #watch_circle_radius:
  #  name: watch_circle_radius
