classname: tsdat.io.retrievers.DefaultRetriever
readers:
  .*:
    classname: pipelines.ndbc.readers.CustomDataReader

coords:
  time:
    data_converters:
      - classname: tsdat.io.converters.StringToDatetime
        format: "%Y-%m-%d %H:%M:%S"
        timezone: UTC
    name: time

data_vars:
  wind_direction:
    name: [WD, WDIR]

  wind_speed:
    name: WSPD

  peak_gust_speed:
    name: GST

  significant_wave_height:
    name: WVHT

  dominant_wave_period:
    name: DPD

  average_wave_period:
    name: APD

  MWD:
    name: MWD

  sea_level_pressure:
    name: [BAR, PRES]

  air_temperature:
    name: ATMP

  sea_surface_temperature:
    name: WTMP

  dewpoint_temperature:
    name: DEWP

  visibility:
    name: VIS

  TIDE:
    name: TIDE
