attrs:
  title: Near-Real Time Surface Ocean Velocity, U.S. West Coast, 1km Resolution
  description: High frequency radar measurements of surface currents in southern CA.
  location_id: sccoos
  dataset_name: hf_radar
  data_level: b1
  qualifier: 6km
  # Other attributes migrated from original file? Need to make sure history isn't overwritten - done

coords:
  time:
    dims: [time]
    dtype: datetime64[s]
    attrs:
      units: Seconds since 1970-01-01 00:00:00
  lat:
    dims: [lat]
    dtype: float32
    attrs:
      units: degrees_north
      long_name: latitude
      standard_name: latitude
      _CoordinateAxisType: Lat
  lon:
    dims: [lon]
    dtype: float32
    attrs:
      units: degrees_east
      long_name: longitude
      standard_name: longitude
      _CoordinateAxisType: Lon

data_vars:
  # time_run:
  #   dims: [time]
  #   dtype: datetime64[ns]
  #   attrs:
  #     units: Seconds since 1970-01-01 00:00:00
  #     long_name: run times for coordinate = time
  #     standard_name: forecast_reference_time
  #     _CoordinateAxisType: RunTime
  u:
    dims: [time, lat, lon]
    dtype: float32
    attrs:
      units: m/s
      long_name: surface_eastward_sea_water_velocity
      standard_name: surface_eastward_sea_water_velocity
      grid_mapping: wgs84
      cell_methods: "depth: mean time: mean"
  v:
    dims: [time, lat, lon]
    dtype: float32
    attrs:
      units: m/s
      long_name: surface_northward_sea_water_velocity
      standard_name: surface_northward_sea_water_velocity
      grid_mapping: wgs84
      cell_methods: "depth: mean time: mean"
  wgs84:
    dims: []
    dtype: int8
    attrs:
      units: degrees
      grid_mapping_name: latitude_longitude
      longitude_of_prime_meridian: 0.0
      semi_major_axis: 6378137.0
      inverse_flattening: 298.257223563
      _CoordinateTransformType: Projection
      _CoordinateAxisTypes: GeoX GeoY
