classname: pipelines.hf_radar.pipeline.SCCOOS_HFRadar

triggers:
  - /^([0-9]){1}$/km

retriever:
  path: pipelines/hf_radar/config/retriever.yaml
  overrides:
    /readers/.*/parameters/resolution: 1km

dataset:
  path: pipelines/hf_radar/config/dataset.yaml

quality:
  path: shared/quality.yaml
storage:
  path: shared/storage.yaml
