classname: tsdat.io.retrievers.DefaultRetriever
readers:
  .*:
    classname: pipelines.hf_radar.readers.FetchHFRadarData
    parameters:
      resolution: 6km
      start_date: "2012-01-01"
      end_date: "2012-02-01"

coords:
  time:
    name: time
  lat:
    name: lat
  lon:
    name: lon

data_vars:
  u:
    name: u
  v:
    name: v
  wgs84:
    name: wgs84
