attrs:
  title: Radiosonde
  description: Sounding data containing measurements from various locations in California.
  dataset_name: radio 
  location_id: ""
  data_level: b0 

coords:
  time:
    dims: [time]
    dtype: datetime64[s]
    attrs:
      long_name: Time
      standard_name: time
      units: Seconds since 1970-01-01 00:00:00 UTC
      timezone: UTC

data_vars:
  pressure_level_data_source:
    dims: []
    dtype: str
    attrs:
      comment: The data source code for pressure levels in the sounding.
      units: "1"

  non_pressure_level_data_source:
    dims: []
    dtype: str
    attrs:
      comment: 
        The data source code for non-pressure levels in the 
        sounding. These include levels whose vertical coordinate
        is only identified by height as well as surface levels without
        either pressure or height.
      units: "1"

  major_level_type:
    dims: [time]
    dtype: float32
    attrs:
      long_name: Major level type indicator
      comment:
        The major level type indicator. It has the following 
        three possible values-
        1 = Standard pressure level (for levels at 1000, 925, 850,
            700, 500, 400, 300, 250, 200, 150, 100, 70, 50, 30, 
            20, 10, 7, 5, 3, 2, and 1 hPa)
        2 = Other pressure level
        3 = Non-pressure level
      units: "1"

  minor_level_type:
    dims: [time]
    dtype: int
    attrs:
      long_name: Minor level type indicator
      comment:
        The minor level type indicator. It has the following 
        three possible values-
        1 = Surface
        2 = Tropopause
        0 = Other
      units: "1"

  pressure:
    dims: [time]
    dtype: int
    attrs:
      long_name: Pressure
      standard_name: pressure
      comment:
        The reported pressure (Pa or mb * 100, e.g., 100000 = 1000 hPa or 1000 mb). -9999 = missing.
      units: hPA

  pressure_processing_flag:
    dims: [time]
    dtype: str
    attrs:
      long_name: Pressure Processing Flag
      comment:
        The pressure processing flag indicating what level of
        climatology-based quality assurance checks were applied. It
        has three possible values-

        blank = Not checked by any climatology checks. If data value 
                not equal to -9999, it passed all other applicable 
                checks.
        A     = Value falls within "tier-1" climatological limits
                based on all days of the year and all times of day
                at the station, but not checked by 
                "tier-2" climatology checks due to 
                insufficient data. 
        B     = Value passes checks based on both the tier-1
                climatology and a "tier-2" climatology specific to
                the time of year and time of day of the data value.
      units: "1"

  geopotential_height:
    dims: [time]
    dtype: int
    attrs:
      long_name: Geopotential Height
      comment:
        The reported geopotential height (meters above sea level).
        This value is often not available at variable-pressure levels.
        The following special values are used-

        -8888 = Value removed by IGRA quality assurance, but valid
                data remain at the same level.
        -9999 = Value missing prior to quality assurance.
      units: m

  geopotential_height_processing_flag:
    dims: [time]
    dtype: str
    attrs:
      long_name: Geopotential Height Processing Flag
      comment:
        The geopotential height processing flag indicating what 
        level of climatology-based quality assurance checks were 
        applied. It has three possible values-

        blank = Not checked by any climatology checks or flag not
                applicable. If data value not equal to -8888 or -9999, 
                it passed all other applicable checks.
        A     = Value falls within "tier-1" climatological limits
                based on all days of the year and all times of day
                at the station, but not checked by 
                "tier-2" climatology checks due to insufficient data. 
        B     = Value passes checks based on both the tier-1
                climatology and a "tier-2" climatology specific to
                the time of year and time of day of the data value.
      units: "1"

  temperature:
    dims: [time]
    dtype: int
    attrs:
      long_name: Temperature
      standard_name: temperature
      comment:
        The reported temperature (degrees C to tenths). The following special values are used-

        -8888 = Value removed by IGRA quality assurance, but valid
                data remain at the same level.
        -9999 = Value missing prior to quality assurance.
      units: degree_C

  temperature_processing_flag:
    dims: [time]
    dtype: str
    attrs:
      long_name: Temperature Processing Flag
      comment:
        The temperature processing flag indicating what 
        level of climatology-based quality assurance checks were 
        applied. It has three possible values-

        blank = Not checked by any climatology checks or flag not
                applicable. If data value not equal to -8888 or -9999, 
                it passed all other applicable checks.
        A     = Value falls within "tier-1" climatological limits
                based on all days of the year and all times of day
                at the station, but not checked by "tier-2" 
                climatology checks due to insufficient data. 
        B     = Value passes checks based on both the tier-1
                climatology and a "tier-2" climatology specific to
                the time of year and time of day of the data value.
      units: "1"

  relative_humidity:
    dims: [time]
    dtype: int
    attrs:
      long_name: Relative Humidity
      standard_name: relative_humidity
      comment:
        The reported relative humidity (Percent to tenths, e.g., 
        11 = 1.1%). The following special values are used-

        -8888 = Value removed by IGRA quality assurance, but valid
                data remain at the same level.
        -9999 = Value missing prior to quality assurance.
      units: "%"

  dewpoint_depression:
    dims: [time]
    dtype: int
    attrs:
      long_name: Dewpoint Depression
      standard_name: dewpoint_depression
      comment:
        the reported dewpoint depression (degrees C to tenths). The following special values are used-

        -8888 = Value removed by IGRA quality assurance, but valid
                data remain at the same level.
        -9999 = Value missing prior to quality assurance.
      units: degree_C

  wind_direction:
    dims: [time]
    dtype: int
    attrs:
      long_name: Wind Direction
      standard_name: wind_direction
      comment:
        the reported wind direction (degrees from north, 
        90 = east). The following special values are used-

        -8888 = Value removed by IGRA quality assurance, but valid
                data remain at the same level.
        -9999 = Value missing prior to quality assurance.
      units: degree

  wind_speed:
    dims: []
    dtype: int
    attrs:
      long_name: Wind Speed
      standard_name: wind_speed
      comment:
        the reported wind speed (meters per second to tenths). The following special values are used-

        -8888 = Value removed by IGRA quality assurance, but valid
                data remain at the same level.
        -9999 = Value missing prior to quality assurance.
      units: m/s

  latitude:
    dims: []
    dtype: float32
    attrs:
      long_name: Latitude
      standard_name: latitude
      comment: Recorded latitude at the instrument location
      units: "degree_N"

  longitude:
    dims: []
    dtype: float32
    attrs:
      long_name: Longitude
      standard_name: longitude
      comment: Recorded longitude at the instrument location
      units: "degree_E"
