classname: pipelines.radiosonde.pipeline.radiosonde

triggers:
  - .*USM00072293.*

retriever:
  path: pipelines/radiosonde/config/retriever.yaml

dataset:
  path: pipelines/radiosonde/config/dataset.yaml

quality:
  path: shared/quality.yaml
storage:
  path: shared/storage.yaml