classname: pipelines.radiosonde.pipeline.radiosonde

triggers:
  - .*USM00072293.*

retriever:
  path: pipelines/radiosonde/config/retriever.yaml

dataset:
  path: pipelines/radiosonde/config/dataset.yaml

quality:
  path: shared/quality.yaml
storage:
  path: shared/storage.yaml

# output_file_name: NWS.radio.OAK.b0.YYYMMD.HHMMSS.nc