classname: pipelines.radiosonde.pipeline.radiosonde

triggers:
  - .*USM00072293.*

retriever:
  path: pipelines/radiosonde/config/retriever.yaml

dataset:
  path: pipelines/radiosonde/config/dataset.yaml
  overrides:
    /attrs/location_id: 78210
    # /data_vars/latitude/data: 33.677 #need to ask
    # /data_vars/longitude/data: -120.213 #need to ask

quality:
  path: shared/quality.yaml
storage:
  path: shared/storage.yaml

# output_file_name: NWS.radio.OAK.b0.YYYMMD.HHMMSS.nc