## Not used, for reference
attrs:
  naming_authority: edu.ucsd.cdip
  keywords_vocabulary: Global Change Master Directory (GCMD) Earth Science Keywords
  date_created: "2023-04-13T23:02:00Z"
  date_issued: "2023-04-13T23:02:00Z"
  date_modified: "2023-04-13T23:02:00Z"
  creator_name: Coastal Data Information Program, SIO/UCSD
  creator_url: http://cdip.ucsd.edu
  creator_email: www@cdip.ucsd.edu
  creator_institution: Scripps Institution of Oceanography, UCSD
  creator_country: USA
  creator_sector: academic
  publisher_name: Coastal Data Information Program, SIO/UCSD
  publisher_url: http://cdip.ucsd.edu
  publisher_email: www@cdip.ucsd.edu
  publisher_country: USA
  publisher_institution: Scripps Institution of Oceanography, UCSD
  institution: Scripps Institution of Oceanography, University of California San Diego
  project: Coastal Data Information Program (CDIP)
  processing_level: QA/QC information available at http://cdip.ucsd.edu/documentation
  standard_name_vocabulary: CF Standard Name Table v79
  Conventions: ACDD-1.3, CF-1.8, IOOS-1.2
  license: These data may be redistributed and used without restriction.
  cdm_data_type: Station
  featureType: timeSeries
  ncei_template_version: NCEI_NetCDF_TimeSeries_Orthogonal_Template_v2.0
  references: http://cdip.ucsd.edu/documentation
  uuid: C2A68CFC-EFEA-40F9-9F93-EEF33772BEBA
  title:
    Directional wave and sea surface temperature measurements collected in situ by
    Datawell DWR-M3 directional buoy located near SCRIPPS NEARSHORE, CA from 2021/11/10
    21:00:00 to 2023/04/13 22:56:40.
  summary:
    Directional wave and sea surface temperature measurements collected in situ by
    Datawell DWR-M3 directional buoy located near SCRIPPS NEARSHORE, CA from 2021/11/10
    21:00:00 to 2023/04/13 22:56:40. A total of 24908 wave samples were analyzed for
    this site, where the water depth is approximately 46 meters.
  keywords:
    EARTH SCIENCE, OCEANS, OCEAN WAVES, GRAVITY WAVES, WIND WAVES, SIGNIFICANT WAVE
    HEIGHT, WAVE FREQUENCY, WAVE PERIOD, WAVE SPECTRA, OCEAN TEMPERATURE, SEA SURFACE
    TEMPERATURE, WATER TEMPERATURE, OCEAN, PACIFIC OCEAN, EASTERN PACIFIC OCEAN
  cdip_station_id: "201"
  platform_id: 201p1
  wmo_id: "46254"
  wmo_platform_code: "46254"
  id: CDIP_201p1_20211110-20230413
  history:
    "2023-02-03T20:44:27Z: dataset created; multiple updates - last run program,
    arguments: process_dw_realtime v2.1, is70387_202302032030 If date_modified is after
    date_created, contact CDIP for details of changes."
  comment:
    This dataset contains data as acquired in real-time, the QC performed upon it is not
    as complete as for historic CDIP datasets. All values are decoded directly from the
    instruments in accordance with the manufacturers documentation EXCEPT for those with
    the attribute :additional_processing which describes further data handling performed
    by CDIP.
  acknowledgment:
    "CDIP is primarily supported by the U.S. Army Corps of Engineers (USACE). Station
    partner: CORDC ; Field operator: CDIP"
  metadata_link: http://cdip.ucsd.edu/metadata/201p1
  infoUrl: http://cdip.ucsd.edu/metadata/201p1
  contributor_name: CDIP, CORDC/USACE
  contributor_role: station operation, station funding
  geospatial_lat_min: 32.86659240722656
  geospatial_lat_max: 32.869407653808594
  geospatial_lat_units: degrees_north
  geospatial_lat_resolution: 9.999999747378752e-05
  geospatial_lon_min: -117.26828002929688
  geospatial_lon_max: -117.26492309570312
  geospatial_lon_units: degrees_east
  geospatial_lon_resolution: 9.999999747378752e-05
  geospatial_vertical_min: 0.0
  geospatial_vertical_max: 0.0
  geospatial_vertical_units: meters
  geospatial_vertical_origin: sea surface
  geospatial_vertical_positive: up
  geospatial_vertical_resolution: 1.0
  time_coverage_start: "2021-11-10T21:00:00Z"
  time_coverage_end: "2023-04-13T22:56:40Z"
  time_coverage_duration: P519DT01H57M
  time_coverage_resolution: PT30M
  source: insitu observations
  instrument: metaInstrumentation
  platform: wave_buoy
  platform_vocabulary: http://mmisw.org/ont/ioos/platform
  platform_name: SCRIPPS NEARSHORE, CA BUOY - 201p1
  DODS.strlen: 0
  DODS.dimName: metaStationNameLength

  location_id: cdip
  dataset_name: "201"
  data_level: c1
  datastream: cdip.201.c1
  description:
    Directional wave and sea surface temperature measurements collected in situ by
    Datawell DWR-M3 directional buoy

coords:
  time:
    dims: [time]
    dtype: datetime64[ns]
    attrs:
      long_name: UTC sample start time
      standard_name: time
      axis: T
      coverage_content_type: coordinate
      bounds: waveTimeBounds
      comment:
        Spectral processing performed on 1600-second samples specified by
        waveTimeBounds.
  frequency:
    dims: [frequency]
    dtype: float32
    attrs:
      long_name: band center frequency
      units: hertz
      standard_name: wave_frequency
      bounds: waveFrequencyBounds
  sst_time:
    dims: [sst_time]
    dtype: datetime64[ns]
    attrs:
      long_name: UTC sample time
      standard_name: time
      axis: T
      coverage_content_type: coordinate
      bounds: sstTimeBounds
  gps_time:
    dims: [gps_time]
    dtype: datetime64[ns]
    attrs:
      long_name: UTC sample time
      standard_name: time
      axis: T
      coverage_content_type: coordinate
      bounds: gpsTimeBounds
  dwr_time:
    dims: [dwr_time]
    dtype: datetime64[ns]
    attrs:
      long_name: UTC sample time
      standard_name: time
      axis: T
      coverage_content_type: coordinate
      bounds: dwrTimeBounds

data_vars:
  wave_flag_primary:
    dims: [time]
    dtype: float32
    attrs:
      long_name: primary wave QC flag
      standard_name: status_flag
      valid_min: 1
      valid_max: 9
      flag_values:
        - 1
        - 2
        - 3
        - 4
        - 9
      flag_meanings:
        - good
        - not_evaluated
        - questionable
        - bad
        - missing
      reference:
        Ocean Data Standards, UNESCO 2013 - IOC Manuals and Guides, 54, Volume 3 Version
        1
      ancillary_variables: wave_flag_secondary
      coverage_content_type: qualityInformation
      units: "1"
  wave_flag_secondary:
    dims: [time]
    dtype: float32
    attrs:
      long_name: secondary wave QC flag
      valid_min: 0
      valid_max: 18
      flag_values:
        - 0
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7
        - 8
        - 9
        - 10
        - 11
        - 12
        - 13
        - 14
        - 15
        - 16
        - 17
        - 18
      flag_meanings:
        - unspecified
        - sensor_issues
        - Hs_out_of_range
        - Tp_out_of_range
        - Ta_out_of_range
        - elevated_check_factors
        - Hs_spike
        - Ta_spike
        - low_freq_energy_spike
        - excessive_low_freq_energy
        - hf_transmission_errors_fixed
        - hf_transmission_errors_present
        - directional_coeffs_out_of_range
        - incomplete_spectrum
        - spectrum_layout_modified
        - too_few_segments
        - inclination_off
        - max_energy_at_highest_freq
        - freq_over_hull_response_limit
      reference: http://cdip.ucsd.edu/documentation
      coverage_content_type: qualityInformation
      units: "1"
  wave_hs:
    dims: [time]
    dtype: float32
    attrs:
      long_name: significant wave height
      units: m
      standard_name: sea_surface_wave_significant_height
      grid_mapping: metaGridMapping
      valid_min: 0.0
      valid_max: 20.0
      ancillary_variables: wave_flag_primary wave_flag_secondary
      ncei_name: WAVE HEIGHT - SIGNIFICANT
  wave_tp:
    dims: [time]
    dtype: float32
    attrs:
      long_name: peak wave period
      units: s
      standard_name: sea_surface_wave_period_at_variance_spectral_density_maximum
      grid_mapping: metaGridMapping
      valid_min: 0.0
      valid_max: 40.0
      ancillary_variables: wave_flag_primary wave_flag_secondary
      ncei_name: WAVE - PEAK PERIOD
  wave_ta:
    dims: [time]
    dtype: float32
    attrs:
      long_name: average wave period
      units: s
      standard_name: sea_surface_wave_mean_period_from_variance_spectral_density_first_frequency_moment
      grid_mapping: metaGridMapping
      valid_min: 0.0
      valid_max: 40.0
      ancillary_variables: wave_flag_primary wave_flag_secondary
      ncei_name: WAVE PERIOD - AVERAGE
      additional_processing:
        Calculated from the full-spectrum, buoy-returned energy density values.
  wave_dp:
    dims: [time]
    dtype: float32
    attrs:
      long_name: peak wave direction
      units: degree_true
      standard_name: sea_surface_wave_from_direction
      grid_mapping: metaGridMapping
      valid_min: 0.0
      valid_max: 360.0
      ancillary_variables: wave_flag_primary wave_flag_secondary
      ncei_name: WAVE DIRECTION
      additional_processing:
        Magnetic declination - INT(metaDeclination) - added to buoy-returned direction
        to shift to degrees true.
  wave_peak_psd:
    dims: [time]
    dtype: float32
    attrs:
      long_name: peak wave power spectral density
      units: m^2/Hz
      grid_mapping: metaGridMapping
      valid_min: 0.0
      valid_max: 5000.0
      ancillary_variables: wave_flag_primary wave_flag_secondary
  wave_tz:
    dims: [time]
    dtype: float32
    attrs:
      long_name: spectral zero-upcross wave period
      units: s
      standard_name: sea_surface_wave_zero_upcrossing_period
      grid_mapping: metaGridMapping
      valid_min: 0.0
      valid_max: 40.0
      ancillary_variables: wave_flag_primary wave_flag_secondary
  wave_source_index:
    dims: [time]
    dtype: float64
    attrs:
      long_name: source file index
      units: "1"
  frequency_flag_primary:
    dims: [frequency]
    dtype: float32
    attrs:
      long_name: primary waveFrequency QC flag
      standard_name: status_flag
      valid_min: 1
      valid_max: 9
      flag_values:
        - 1
        - 2
        - 3
        - 4
        - 9
      flag_meanings:
        - good
        - not_evaluated
        - questionable
        - bad
        - missing
      reference:
        Ocean Data Standards, UNESCO 2013 - IOC Manuals and Guides, 54, Volume 3 Version
        1
      ancillary_variables: frequency_flag_secondary
      coverage_content_type: qualityInformation
      units: "1"
  frequency_flag_secondary:
    dims: [frequency]
    dtype: float32
    attrs:
      long_name: secondary waveFrequency QC flag
      valid_min: 0
      valid_max: 2
      flag_values:
        - 0
        - 1
        - 2
      flag_meanings:
        - unspecified
        - out_of_range
        - above_hull_response_limit
      reference: http://cdip.ucsd.edu/documentation
      coverage_content_type: qualityInformation
      units: "1"
  wave_bandwidth:
    dims: [frequency]
    dtype: float32
    attrs:
      long_name: bandwidth
      units: Hz
      ncei_name: WAVE ENERGY - WIDTH OF SPECTRAL BANDS
  sst_flag_primary:
    dims: [sst_time]
    dtype: float32
    attrs:
      long_name: primary sst QC flag
      standard_name: status_flag
      valid_min: 1
      valid_max: 9
      flag_values:
        - 1
        - 2
        - 3
        - 4
        - 9
      flag_meanings:
        - good
        - not_evaluated
        - questionable
        - bad
        - missing
      reference:
        Ocean Data Standards, UNESCO 2013 - IOC Manuals and Guides, 54, Volume 3 Version
        1
      ancillary_variables: sst_flag_secondary
      coverage_content_type: qualityInformation
      units: "1"
  sst_flag_secondary:
    dims: [sst_time]
    dtype: float32
    attrs:
      long_name: secondary sst QC flag
      valid_min: 0
      valid_max: 7
      flag_values:
        - 0
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7
      flag_meanings:
        - unspecified
        - sensor_issues
        - SST_out_of_range
        - SST_spike
        - SST_max_change_exceeded
        - hf_transmission_errors_fixed
        - hf_transmission_errors_present
        - reference_temperature_off
      reference: http://cdip.ucsd.edu/documentation
      coverage_content_type: qualityInformation
      units: "1"
  sst:
    dims: [sst_time]
    dtype: float32
    attrs:
      long_name: sea surface temperature
      units: degree_C
      standard_name: sea_surface_temperature
      grid_mapping: metaGridMapping
      valid_min: -5.0
      valid_max: 46.150001525878906
      ancillary_variables: sst_flag_primary sst_flag_secondary
      ncei_name: SEA SURFACE TEMPERATURE
      cell_methods: "sstTime: point"
  sst_source_index:
    dims: [sst_time]
    dtype: float64
    attrs:
      long_name: source file index
      units: "1"
  sst_reference_temp:
    dims: [sst_time]
    dtype: float32
    attrs:
      long_name: reference temperature
      units: degree_C
  gps_status_flags:
    dims: [gps_time]
    dtype: float32
    attrs:
      long_name: gps data flags
      flag_masks:
        - 1
        - 2
        - 4
        - 8
      flag_meanings:
        - module_ok
        - new_fix
        - figure_of_merit
        - hf_transmission_error
      comment:
        Good GPS positions will have module_ok and new_fix set, i.e. gpsStatusFlags=3.
        All other positions should be ignored. Note that some records with
        gpsStatusFlags=3 may also be erroneous, these values are not subject to any
        quality control.
      units: "1"
  gps_latitude:
    dims: [gps_time]
    dtype: float32
    attrs:
      long_name: buoy latitude
      units: degree_north
      valid_min: -90.0
      valid_max: 90.0
      ncei_name: LATITUDE
      cell_methods: "gpsTime: point"
      ancillary_variables: gpsStatusFlags
  gps_longitude:
    dims: [gps_time]
    dtype: float32
    attrs:
      long_name: buoy longitude
      units: degree_east
      valid_min: -180.0
      valid_max: 180.0
      ncei_name: LONGITUDE
      cell_methods: "gpsTime: point"
      ancillary_variables: gpsStatusFlags
  gps_source_index:
    dims: [gps_time]
    dtype: float64
    attrs:
      long_name: source file index
      units: "1"
  dwr_source_index:
    dims: [dwr_time]
    dtype: float64
    attrs:
      long_name: source file index
      units: "1"
  dwr_battery_level:
    dims: [dwr_time]
    dtype: float64
    attrs:
      long_name: battery level
      valid_min: 0
      valid_max: 7
      units: "1"
  dwr_z_accelerometer_offset:
    dims: [dwr_time]
    dtype: float32
    attrs:
      long_name: vertical accelerometer offset
      units: m/s^2
  dwr_x_accelerometer_offset:
    dims: [dwr_time]
    dtype: float32
    attrs:
      long_name: x-axis accelerometer offset
      units: m/s^2
  dwr_y_accelerometer_offset:
    dims: [dwr_time]
    dtype: float32
    attrs:
      long_name: y-axis accelerometer offset
      units: m/s^2
  dwr_orientation:
    dims: [dwr_time]
    dtype: float32
    attrs:
      long_name: buoy orientation
      units: deg
      standard_name: platform_orientation
  dwr_inclination:
    dims: [dwr_time]
    dtype: float32
    attrs:
      long_name: magnetic inclination
      units: deg
  dwr_battery_weeks_of_life:
    dims: [dwr_time]
    dtype: float64
    attrs:
      long_name: battery weeks of life
      units: weeks
  wave_energy_density:
    dims: [time, frequency]
    dtype: float32
    attrs:
      long_name: band energy density
      units: m^2 s
      standard_name: sea_surface_wave_variance_spectral_density
      grid_mapping: metaGridMapping
      valid_min: 0.0
      ancillary_variables:
        wave_flag_primary frequency_flag_primary wave_flag_secondary
        frequency_flag_secondary
      ncei_name: WAVE ENERGY - SPECTRAL VALUE
  wave_mean_direction:
    dims: [time, frequency]
    dtype: float32
    attrs:
      long_name: band mean direction
      units: degree_true
      standard_name: sea_surface_wave_from_direction
      grid_mapping: metaGridMapping
      valid_min: 0.0
      valid_max: 360.0
      ancillary_variables:
        wave_flag_primary frequency_flag_primary wave_flag_secondary
        frequency_flag_secondary
      ncei_name: WAVE DIRECTION - AVERAGE
      additional_processing:
        Magnetic declination (metaDeclination) added to buoy-returned direction to shift
        to degrees true.
  wave_a1_value:
    dims: [time, frequency]
    dtype: float32
    attrs:
      long_name: band a1 Fourier coefficient
      grid_mapping: metaGridMapping
      valid_min: -1.0
      valid_max: 1.0
      ancillary_variables:
        wave_flag_primary frequency_flag_primary wave_flag_secondary
        frequency_flag_secondary
      ncei_name: WAVE DATA - ANGULAR FOURIER COEFFICIENTS
      additional_processing:
        Calculated relative to true north from the buoy-returned mean dir, spread, m2,
        and n2.
      units: "1"
  wave_b1_value:
    dims: [time, frequency]
    dtype: float32
    attrs:
      long_name: band b1 Fourier coefficient
      grid_mapping: metaGridMapping
      valid_min: -1.0
      valid_max: 1.0
      ancillary_variables:
        wave_flag_primary frequency_flag_primary wave_flag_secondary
        frequency_flag_secondary
      ncei_name: WAVE DATA - ANGULAR FOURIER COEFFICIENTS
      additional_processing:
        Calculated relative to true north from the buoy-returned mean dir, spread, m2,
        and n2.
      units: "1"
  wave_a2_value:
    dims: [time, frequency]
    dtype: float32
    attrs:
      long_name: band a2 Fourier coefficient
      grid_mapping: metaGridMapping
      valid_min: -1.0
      valid_max: 1.0
      ancillary_variables:
        wave_flag_primary frequency_flag_primary wave_flag_secondary
        frequency_flag_secondary
      ncei_name: WAVE DATA - ANGULAR FOURIER COEFFICIENTS
      additional_processing:
        Calculated relative to true north from the buoy-returned mean dir, spread, m2,
        and n2.
      units: "1"
  wave_b2_value:
    dims: [time, frequency]
    dtype: float32
    attrs:
      long_name: band b2 Fourier coefficient
      grid_mapping: metaGridMapping
      valid_min: -1.0
      valid_max: 1.0
      ancillary_variables:
        wave_flag_primary frequency_flag_primary wave_flag_secondary
        frequency_flag_secondary
      ncei_name: WAVE DATA - ANGULAR FOURIER COEFFICIENTS
      additional_processing:
        Calculated relative to true north from the buoy-returned mean dir, spread, m2,
        and n2.
      units: "1"
  wave_check_factor:
    dims: [time, frequency]
    dtype: float32
    attrs:
      long_name: band check factor (inverse of wave ellipticity)
      grid_mapping: metaGridMapping
      valid_min: 0.0
      valid_max: 2.549999952316284
      ancillary_variables:
        wave_flag_primary frequency_flag_primary wave_flag_secondary
        frequency_flag_secondary
      units: "1"
  wave_spread:
    dims: [time, frequency]
    dtype: float32
    attrs:
      long_name: band directional spread
      units: deg
      grid_mapping: metaGridMapping
      valid_min: 0.0
      valid_max: 90.0
      ancillary_variables:
        wave_flag_primary frequency_flag_primary wave_flag_secondary
        frequency_flag_secondary
  wave_m2_value:
    dims: [time, frequency]
    dtype: float32
    attrs:
      long_name: band centered sine Fourier coefficient
      grid_mapping: metaGridMapping
      valid_min: -1.0
      valid_max: 1.0
      ancillary_variables:
        wave_flag_primary frequency_flag_primary wave_flag_secondary
        frequency_flag_secondary
      units: "1"
  wave_n2_value:
    dims: [time, frequency]
    dtype: float32
    attrs:
      long_name: band centered cosine Fourier coefficient
      grid_mapping: metaGridMapping
      valid_min: -1.0
      valid_max: 1.0
      ancillary_variables:
        wave_flag_primary frequency_flag_primary wave_flag_secondary
        frequency_flag_secondary
      units: "1"
