attrs:
  title:
    Directional wave and sea surface temperature measurements collected in situ by
    Datawell DWR-M3 directional buoy.
  description:
    Directional wave and sea surface temperature measurements collected in situ by
    Datawell DWR-M3 directional buoy
  location_id: cdip
  dataset_name: "000" # Updated in pipeline hook
  data_level: c1
  # Other attributes migrated from original file

coords:
  time:
    dims: [time]
    dtype: datetime64[ns]
    attrs:
      units: Seconds since 1970-01-01 00:00:00
      long_name: UTC sample start time
      standard_name: time
      axis: T
      bounds: waveTimeBounds
      comment:
        Spectral processing performed on 1600-second samples specified by
        waveTimeBounds.
  frequency:
    dims: [frequency]
    dtype: float32
    attrs:
      long_name: band center frequency
      units: hertz
      standard_name: wave_frequency
      bounds: waveFrequencyBounds
  sst_time:
    dims: [sst_time]
    dtype: datetime64[ns]
    attrs:
      units: Seconds since 1970-01-01 00:00:00
      long_name: UTC sample time
      standard_name: time
      axis: T
      bounds: sstTimeBounds
  gps_time:
    dims: [gps_time]
    dtype: datetime64[ns]
    attrs:
      units: Seconds since 1970-01-01 00:00:00
      long_name: UTC sample time
      standard_name: time
      axis: T
      bounds: gpsTimeBounds
  dwr_time:
    dims: [dwr_time]
    dtype: datetime64[ns]
    attrs:
      units: Seconds since 1970-01-01 00:00:00
      long_name: UTC sample time
      standard_name: time
      axis: T
      bounds: dwrTimeBounds

data_vars:
  # meta_deploy_latitude:
  #   dims: []
  #   dtype: float32
  #   attrs:
  #     standard_name: latitude
  #     units: deg_north
  #     valid_min: -90.0
  #     valid_max: 90.0
  #     axis: Y
  #     ncei_name: LATITUDE
  # meta_deploy_longitude:
  #   dims: []
  #   dtype: float32
  #   attrs:
  #     standard_name: longitude
  #     units: deg_east
  #     valid_min: -180.0
  #     valid_max: 180.0
  #     axis: X
  #     ncei_name: LONGITUDE
  wave_flag_primary:
    dims: [time]
    dtype: float32
    attrs:
      units: "1"
      long_name: primary wave QC flag
      valid_min: 1
      valid_max: 9
      flag_values:
        - 1
        - 2
        - 3
        - 4
        - 9
      flag_meanings: [good, not_evaluated, questionable, bad, missing]
      reference:
        Ocean Data Standards, UNESCO 2013 - IOC Manuals and Guides, 54, Volume 3 Version
        1
      ancillary_variables: wave_flag_secondary
  wave_flag_secondary:
    dims: [time]
    dtype: float32
    attrs:
      units: "1"
      long_name: secondary wave QC flag
      valid_min: 0
      valid_max: 18
      flag_values:
        - 0
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7
        - 8
        - 9
        - 10
        - 11
        - 12
        - 13
        - 14
        - 15
        - 16
        - 17
        - 18
      flag_meanings:
        [
          unspecified,
          sensor_issues,
          Hs_out_of_range,
          Tp_out_of_range,
          Ta_out_of_range,
          elevated_check_factors,
          Hs_spike,
          Ta_spike,
          low_freq_energy_spike,
          excessive_low_freq_energy,
          hf_transmission_errors_fixed,
          hf_transmission_errors_present,
          directional_coeffs_out_of_range,
          incomplete_spectrum,
          spectrum_layout_modified,
          too_few_segments,
          inclination_off,
          max_energy_at_highest_freq,
          freq_over_hull_response_limit,
        ]
      reference: http://cdip.ucsd.edu/documentation
  wave_hs:
    dims: [time]
    dtype: float32
    attrs:
      long_name: significant wave height
      units: m
      standard_name: sea_surface_wave_significant_height
      grid_mapping: metaGridMapping
      valid_min: 0.0
      valid_max: 20.0
      ancillary_variables: wave_flag_primary wave_flag_secondary
      ncei_name: WAVE HEIGHT - SIGNIFICANT
  wave_tp:
    dims: [time]
    dtype: float32
    attrs:
      long_name: peak wave period
      units: s
      standard_name: sea_surface_wave_period_at_variance_spectral_density_maximum
      grid_mapping: metaGridMapping
      valid_min: 0.0
      valid_max: 40.0
      ancillary_variables: wave_flag_primary wave_flag_secondary
      ncei_name: WAVE - PEAK PERIOD
  wave_ta:
    dims: [time]
    dtype: float32
    attrs:
      long_name: average wave period
      units: s
      standard_name: sea_surface_wave_mean_period_from_variance_spectral_density_first_frequency_moment
      grid_mapping: metaGridMapping
      valid_min: 0.0
      valid_max: 40.0
      ancillary_variables: wave_flag_primary wave_flag_secondary
      ncei_name: WAVE PERIOD - AVERAGE
      additional_processing:
        Calculated from the full-spectrum, buoy-returned energy density values.
  wave_dp:
    dims: [time]
    dtype: float32
    attrs:
      long_name: peak wave direction
      units: degree_true
      standard_name: sea_surface_wave_from_direction
      grid_mapping: metaGridMapping
      valid_min: 0.0
      valid_max: 360.0
      ancillary_variables: wave_flag_primary wave_flag_secondary
      ncei_name: WAVE DIRECTION
      additional_processing:
        Magnetic declination - INT(metaDeclination) - added to buoy-returned direction
        to shift to degrees true.
  wave_peak_psd:
    dims: [time]
    dtype: float32
    attrs:
      long_name: peak wave power spectral density
      units: m^2/Hz
      grid_mapping: metaGridMapping
      valid_min: 0.0
      valid_max: 5000.0
      ancillary_variables: wave_flag_primary wave_flag_secondary
  wave_tz:
    dims: [time]
    dtype: float32
    attrs:
      long_name: spectral zero-upcross wave period
      units: s
      standard_name: sea_surface_wave_zero_upcrossing_period
      grid_mapping: metaGridMapping
      valid_min: 0.0
      valid_max: 40.0
      ancillary_variables: wave_flag_primary wave_flag_secondary
  wave_source_index:
    dims: [time]
    dtype: float32
    attrs:
      units: "1"
      long_name: source file index
  frequency_flag_primary:
    dims: [frequency]
    dtype: float32
    attrs:
      units: "1"
      long_name: primary waveFrequency QC flag
      valid_min: 1
      valid_max: 9
      flag_values:
        - 1
        - 2
        - 3
        - 4
        - 9
      flag_meanings: [good, not_evaluated, questionable, bad, missing]
      reference:
        Ocean Data Standards, UNESCO 2013 - IOC Manuals and Guides, 54, Volume 3 Version
        1
      ancillary_variables: frequency_flag_secondary
  frequency_flag_secondary:
    dims: [frequency]
    dtype: float32
    attrs:
      units: "1"
      long_name: secondary waveFrequency QC flag
      valid_min: 0
      valid_max: 2
      flag_values:
        - 0
        - 1
        - 2
      flag_meanings: [unspecified, out_of_range, above_hull_response_limit]
      reference: http://cdip.ucsd.edu/documentation
  wave_bandwidth:
    dims: [frequency]
    dtype: float32
    attrs:
      long_name: bandwidth
      units: Hz
      ncei_name: WAVE ENERGY - WIDTH OF SPECTRAL BANDS
  sst_flag_primary:
    dims: [sst_time]
    dtype: float32
    attrs:
      units: "1"
      long_name: primary sst QC flag
      valid_min: 1
      valid_max: 9
      flag_values:
        - 1
        - 2
        - 3
        - 4
        - 9
      flag_meanings: [good, not_evaluated, questionable, bad, missing]
      reference:
        Ocean Data Standards, UNESCO 2013 - IOC Manuals and Guides, 54, Volume 3 Version
        1
      ancillary_variables: sst_flag_secondary
  sst_flag_secondary:
    dims: [sst_time]
    dtype: float32
    attrs:
      units: "1"
      long_name: secondary sst QC flag
      valid_min: 0
      valid_max: 7
      flag_values:
        - 0
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7
      flag_meanings:
        [
          unspecified,
          sensor_issues,
          SST_out_of_range,
          SST_spike,
          SST_max_change_exceeded,
          hf_transmission_errors_fixed,
          hf_transmission_errors_present,
          reference_temperature_off,
        ]
      reference: http://cdip.ucsd.edu/documentation
  sst:
    dims: [sst_time]
    dtype: float32
    attrs:
      long_name: sea surface temperature
      units: degree_C
      standard_name: sea_surface_temperature
      grid_mapping: metaGridMapping
      valid_min: -5.0
      valid_max: 46.150001525878906
      ancillary_variables: sst_flag_primary sst_flag_secondary
      ncei_name: SEA SURFACE TEMPERATURE
      cell_methods: "sstTime: point"
  sst_source_index:
    dims: [sst_time]
    dtype: float32
    attrs:
      units: "1"
      long_name: source file index
  sst_reference_temp:
    dims: [sst_time]
    dtype: float32
    attrs:
      long_name: reference temperature
      units: degree_C
  gps_status_flags:
    dims: [gps_time]
    dtype: float32
    attrs:
      units: "1"
      long_name: gps data flags
      flag_masks:
        - 1
        - 2
        - 4
        - 8
      flag_meanings: [module_ok, new_fix, figure_of_merit, hf_transmission_error]
      comment:
        Good GPS positions will have module_ok and new_fix set, i.e. gpsStatusFlags=3.
        All other positions should be ignored. Note that some records with
        gpsStatusFlags=3 may also be erroneous, these values are not subject to any
        quality control.
  gps_latitude:
    dims: [gps_time]
    dtype: float32
    attrs:
      long_name: buoy latitude
      units: degree_N
      valid_min: -90.0
      valid_max: 90.0
      ncei_name: LATITUDE
      cell_methods: "gpsTime: point"
      ancillary_variables: gpsStatusFlags
  gps_longitude:
    dims: [gps_time]
    dtype: float32
    attrs:
      long_name: buoy longitude
      units: degree_E
      valid_min: -180.0
      valid_max: 180.0
      ncei_name: LONGITUDE
      cell_methods: "gpsTime: point"
      ancillary_variables: gpsStatusFlags
  gps_source_index:
    dims: [gps_time]
    dtype: float32
    attrs:
      units: "1"
      long_name: source file index
  dwr_source_index:
    dims: [dwr_time]
    dtype: float32
    attrs:
      units: "1"
      long_name: source file index
  dwr_battery_level:
    dims: [dwr_time]
    dtype: float32
    attrs:
      units: "1"
      long_name: battery level
      valid_min: 0
      valid_max: 7
  dwr_z_accelerometer_offset:
    dims: [dwr_time]
    dtype: float32
    attrs:
      long_name: vertical accelerometer offset
      units: m/s^2
  dwr_x_accelerometer_offset:
    dims: [dwr_time]
    dtype: float32
    attrs:
      long_name: x-axis accelerometer offset
      units: m/s^2
  dwr_y_accelerometer_offset:
    dims: [dwr_time]
    dtype: float32
    attrs:
      long_name: y-axis accelerometer offset
      units: m/s^2
  dwr_orientation:
    dims: [dwr_time]
    dtype: float32
    attrs:
      long_name: buoy orientation
      units: deg
      standard_name: platform_orientation
  dwr_inclination:
    dims: [dwr_time]
    dtype: float32
    attrs:
      long_name: magnetic inclination
      units: deg
  dwr_battery_weeks_of_life:
    dims: [dwr_time]
    dtype: float32
    attrs:
      long_name: battery weeks of life
      units: weeks
  # meta_station_name:
  #   dims: []
  #   dtype: "|S64"
  #   attrs:
  #     units: "1"
  #     long_name: station name
  #     standard_name: platform_id
  #     cf_role: timeseries_id
  # meta_platform:
  #   dims: []
  #   dtype: "|S64"
  #   attrs:
  #     units: "1"
  #     long_name: platform_attributes
  #     make_model: Datawell DWR-M3 directional buoy
  #     serial_number: "Hull: 30399; hatchcover: 70387"
  #     documentation_url: http://datawell.nl
  #     mooring: Datawell-compliant
  #     mooring_length_meters: 73.0
  # meta_instrumentation:
  #   dims: []
  #   dtype: "|S64"
  #   attrs:
  #     units: "1"
  #     long_name: instrumentation_attributes
  #     make_model: Datawell DWR-M3 directional buoy
  #     serial_number: "Hull: 30399; hatchcover: 70387"
  #     documentation_url: http://datawell.nl
  #     mooring: Datawell-compliant
  #     mooring_length_meters: 73.0
  # meta_water_depth:
  #   dims: []
  #   dtype: float32
  #   attrs:
  #     standard_name: sea_floor_depth_below_sea_surface
  #     long_name: water depth
  #     units: m
  #     ncei_name: DEPTH - BOTTOM
  # meta_declination:
  #   dims: []
  #   dtype: float32
  #   attrs:
  #     long_name: magnetic declination
  #     units: deg
  # meta_grid_mapping:
  #   dims: []
  #   dtype: "|S64"
  #   attrs:
  #     units: "1"
  #     grid_mapping_name: latitude_longitude
  #     longitude_of_prime_meridian: 0.0
  #     semi_major_axis: 6378137.0
  #     inverse_flattening: 298.257223563
  wave_energy_density:
    dims: [time, frequency]
    dtype: float32
    attrs:
      long_name: band energy density
      units: m^2 s
      standard_name: sea_surface_wave_variance_spectral_density
      grid_mapping: metaGridMapping
      valid_min: 0.0
      ancillary_variables:
        wave_flag_primary frequency_flag_primary wave_flag_secondary
        frequency_flag_secondary
      ncei_name: WAVE ENERGY - SPECTRAL VALUE
  wave_mean_direction:
    dims: [time, frequency]
    dtype: float32
    attrs:
      long_name: band mean direction
      units: degree_true
      standard_name: sea_surface_wave_from_direction
      grid_mapping: metaGridMapping
      valid_min: 0.0
      valid_max: 360.0
      ancillary_variables:
        wave_flag_primary frequency_flag_primary wave_flag_secondary
        frequency_flag_secondary
      ncei_name: WAVE DIRECTION - AVERAGE
      additional_processing:
        Magnetic declination (metaDeclination) added to buoy-returned direction to shift
        to degrees true.
  wave_a1_value:
    dims: [time, frequency]
    dtype: float32
    attrs:
      units: "1"
      long_name: band a1 Fourier coefficient
      grid_mapping: metaGridMapping
      valid_min: -1.0
      valid_max: 1.0
      ancillary_variables:
        wave_flag_primary frequency_flag_primary wave_flag_secondary
        frequency_flag_secondary
      ncei_name: WAVE DATA - ANGULAR FOURIER COEFFICIENTS
      additional_processing:
        Calculated relative to true north from the buoy-returned mean dir, spread, m2,
        and n2.
  wave_b1_value:
    dims: [time, frequency]
    dtype: float32
    attrs:
      units: "1"
      long_name: band b1 Fourier coefficient
      grid_mapping: metaGridMapping
      valid_min: -1.0
      valid_max: 1.0
      ancillary_variables:
        wave_flag_primary frequency_flag_primary wave_flag_secondary
        frequency_flag_secondary
      ncei_name: WAVE DATA - ANGULAR FOURIER COEFFICIENTS
      additional_processing:
        Calculated relative to true north from the buoy-returned mean dir, spread, m2,
        and n2.
  wave_a2_value:
    dims: [time, frequency]
    dtype: float32
    attrs:
      units: "1"
      long_name: band a2 Fourier coefficient
      grid_mapping: metaGridMapping
      valid_min: -1.0
      valid_max: 1.0
      ancillary_variables:
        wave_flag_primary frequency_flag_primary wave_flag_secondary
        frequency_flag_secondary
      ncei_name: WAVE DATA - ANGULAR FOURIER COEFFICIENTS
      additional_processing:
        Calculated relative to true north from the buoy-returned mean dir, spread, m2,
        and n2.
  wave_b2_value:
    dims: [time, frequency]
    dtype: float32
    attrs:
      units: "1"
      long_name: band b2 Fourier coefficient
      grid_mapping: metaGridMapping
      valid_min: -1.0
      valid_max: 1.0
      ancillary_variables:
        wave_flag_primary frequency_flag_primary wave_flag_secondary
        frequency_flag_secondary
      ncei_name: WAVE DATA - ANGULAR FOURIER COEFFICIENTS
      additional_processing:
        Calculated relative to true north from the buoy-returned mean dir, spread, m2,
        and n2.
  wave_check_factor:
    dims: [time, frequency]
    dtype: float32
    attrs:
      units: "1"
      long_name: band check factor (inverse of wave ellipticity)
      grid_mapping: metaGridMapping
      valid_min: 0.0
      valid_max: 2.549999952316284
      ancillary_variables:
        wave_flag_primary frequency_flag_primary wave_flag_secondary
        frequency_flag_secondary
  wave_spread:
    dims: [time, frequency]
    dtype: float32
    attrs:
      long_name: band directional spread
      units: deg
      grid_mapping: metaGridMapping
      valid_min: 0.0
      valid_max: 90.0
      ancillary_variables:
        wave_flag_primary frequency_flag_primary wave_flag_secondary
        frequency_flag_secondary
  wave_m2_value:
    dims: [time, frequency]
    dtype: float32
    attrs:
      units: "1"
      long_name: band centered sine Fourier coefficient
      grid_mapping: metaGridMapping
      valid_min: -1.0
      valid_max: 1.0
      ancillary_variables:
        wave_flag_primary frequency_flag_primary wave_flag_secondary
        frequency_flag_secondary
  wave_n2_value:
    dims: [time, frequency]
    dtype: float32
    attrs:
      units: "1"
      long_name: band centered cosine Fourier coefficient
      grid_mapping: metaGridMapping
      valid_min: -1.0
      valid_max: 1.0
      ancillary_variables:
        wave_flag_primary frequency_flag_primary wave_flag_secondary
        frequency_flag_secondary
