managers:
  #---------------------------------------------------------------
  - name: Fail if missing coordinates
    checker:
      classname: tsdat.qc.checkers.CheckMissing
    handlers:
      - classname: tsdat.qc.handlers.FailPipeline
        parameters:
          context: Coordinate variables cannot be missing.
    apply_to:
      - COORDS
