classname: pipelines.noaa_weber_wuertz_wind.pipeline.NoaaWeberWuertzWind

triggers:
  # DEVELOPER: Update regex patterns that should trigger this pipeline
  - .*/noaa_weber_wuertz_wind/test/data/input/pts/.*/.*/pts.*w

retriever:
  path: pipelines/noaa_weber_wuertz_wind/config/retriever.yaml

dataset:
  path: pipelines/noaa_weber_wuertz_wind/config/dataset.yaml
  overrides:
    /attrs/location_id: pts
    /data_vars/elevation/data: 11
    /data_vars/latitude/data: 36.30
    /data_vars/longitude/data: -121.89

quality:
  path: shared/quality.yaml
storage:
  path: shared/storage.yaml