classname: pipelines.noaa_weber_wuertz_wind.pipeline.NoaaWeberWuertzWind

triggers:
  # DEVELOPER: Update regex patterns that should trigger this pipeline
  - .*/noaa_weber_wuertz_wind/test/data/input/cco/.*/.*/cco.*w

retriever:
  path: pipelines/noaa_weber_wuertz_wind/config/retriever.yaml

dataset:
  path: pipelines/noaa_weber_wuertz_wind/config/dataset.yaml
  overrides:
    /attrs/location_id: cco
    /data_vars/elevation/data: 41
    /data_vars/latitude/data: 39.69
    /data_vars/longitude/data: -121.91

quality:
  path: shared/quality.yaml
storage:
  path: shared/storage.yaml