classname: pipelines.noaa_weber_wuertz_wind.pipeline.NoaaWeberWuertzWind

triggers:
  - .*/noaa_weber_wuertz_wind/test/data/input/tci/.*/.*/tci.*w

retriever:
  path: pipelines/noaa_weber_wuertz_wind/config/retriever.yaml

dataset:
  path: pipelines/noaa_weber_wuertz_wind/config/dataset.yaml
  overrides:
    /attrs/location_id: tci
    /data_vars/elevation/data: 0
    /data_vars/latitude/data: 38.10
    /data_vars/longitude/data: -121.65

quality:
  path: shared/quality.yaml
storage:
  path: shared/storage.yaml
