classname: tsdat.io.retrievers.DefaultRetriever
readers:
  .*:
    classname: pipelines.noaa_weber_wuertz_wind.readers.CustomDataReader

coords:
  time:
    data_converters:
      - classname: tsdat.io.converters.StringToDatetime
        format: "%Y-%m-%d %H:%M:%S"
        timezone: UTC
    name: time

data_vars:
  height:
    name: height

  wind_speed:
    name: wind_speed

  wind_direction:
    name: wind_direction

  qc_wind:
    name: QC_wind

  radial_velocity_beam_1:
    name: radial_velocity_beam_1

  radial_velocity_beam_2:
    name: radial_velocity_beam_2

  radial_velocity_beam_3:
    name: radial_velocity_beam_3

  number_of_records_in_mean_beam_1:
    name: number_of_records_in_mean_beam_1

  number_of_records_in_mean_beam_2:
    name: number_of_records_in_mean_beam_2

  number_of_records_in_mean_beam_3:
    name: number_of_records_in_mean_beam_3

  SNR_beam_1:
    name: SNR_beam_1

  SNR_beam_2:
    name: SNR_beam_2

  SNR_beam_3:
    name: SNR_beam_3

  qc_radial_velocity_beam_1:
    name: qc_radial_velocity_beam_1

  qc_radial_velocity_beam_2:
    name: qc_radial_velocity_beam_2

  qc_radial_velocity_beam_3:
    name: qc_radial_velocity_beam_3

  latitude:
    name: latitude

  longitude:
    name: longitude

  elevation:
    name: elevation
