classname: pipelines.noaa_weber_wuertz_temp.pipeline.NoaaWeberWuertzTemp

triggers:
  # DEVELOPER: Update regex patterns that should trigger this pipeline
  - .*/noaa_weber_wuertz_temp/test/data/input/bby/.*/.*/bby.*t

retriever:
  path: pipelines/noaa_weber_wuertz_temp/config/retriever.yaml

dataset:
  path: pipelines/noaa_weber_wuertz_temp/config/dataset.yaml
  overrides:
    /attrs/location_id: bby
    /data_vars/elevation/data: 13
    /data_vars/latitude/data: 38.32
    /data_vars/longitude/data: -123.07

quality:
  path: shared/quality.yaml
storage:
  path: shared/storage.yaml
