classname: pipelines.noaa_weber_wuertz_temp.pipeline.NoaaWeberWuertzTemp

triggers:
  # DEVELOPER: Update regex patterns that should trigger this pipeline
  - .*/noaa_weber_wuertz_temp/test/data/input/sns/.*/.*/sns.*t

retriever:
  path: pipelines/noaa_weber_wuertz_temp/config/retriever.yaml

dataset:
  path: pipelines/noaa_weber_wuertz_temp/config/dataset.yaml
  overrides:
    /attrs/location_id: sns
    /data_vars/elevation/data: 17
    /data_vars/latitude/data: 33.28
    /data_vars/longitude/data: -119.52

quality:
  path: shared/quality.yaml
storage:
  path: shared/storage.yaml
