# DEVELOPER: Add attrs and coords/variables to specify the output data structure

attrs:
  title: CSI-Datalogger-Surface-Met
  description: noaa csi datalogger surface met ascii files to netcdf
  location_id: acv
  dataset_name: csi_datalogger_surface_met
  data_level: b0

coords:
  time:
    dims: [time]
    dtype: datetime64[s]
    attrs:
      units: Seconds since 1970-01-01 00:00:00 UTC
      long_name: Time
      standard_name: time
      timezone: UTC

data_vars:
  pressure:
    dims: [time]
    dtype: float
    attrs:
      long_name: Pressure
      standard_name: pressure
      units: mbar

  temperature:
    dims: [time]
    dtype: float
    attrs:
      long_name: Temperature
      standard_name: temperature
      units: degC

  relative_humidity:
    dims: [time]
    dtype: float
    attrs:
      long_name: Relative Humidity
      standard_name: relative_humidity
      units: "%"

  scalar_wind_speed:
    dims: [time]
    dtype: float
    attrs:
      long_name: Scalar Wind Speed
      standard_name: wind_speed
      units: m/s

  wind_direction:
    dims: [time]
    dtype: float
    attrs:
      long_name: Wind Diection
      standard_name: wind_direction
      units: degrees

  precipitation:
    dims: [time]
    dtype: float
    attrs:
      long_name: Precipitation
      standard_name: lwe_thickness_of_precipitation_amount
      units: m

  solar_radiation:
    dims: [time]
    dtype: float
    attrs:
      long_name: Solar Radiation
      standard_name: solar_irradiance
      units: W/m^2

  latitude:
    data: 40.97
    dims: []
    dtype: float32
    attrs:
      long_name: North latitude
      standard_name: latitude
      comment: Recorded latitude at the instrument location
      units: degree_N

  longitude:
    data: -124.11
    dims: []
    dtype: float32
    attrs:
      long_name: East longitude
      standard_name: longitude
      comment: Recorded longitude at the instrument location
      units: degree_E

  elevation:
    data: 56
    dims: []
    dtype: float32
    attrs:
      long_name: Site elevation
      units: m
