classname: pipelines.csi_datalogger_surface_met.pipeline.CsiDataloggerSurfaceMet

triggers:
  # DEVELOPER: Update regex patterns that should trigger this pipeline
  - /share/home/ocoleman/upprocessed-met/input/pan/..../.../...........m

retriever:
  path: pipelines/csi_datalogger_surface_met/config/retriever.yaml

dataset:
  path: pipelines/csi_datalogger_surface_met/config/dataset.yaml
  overrides:
    /attrs/location_id: pan
    /data_vars/latitude/data: 38.930000
    /data_vars/longitude/data: -123.730003
    /data_vars/elevation/data: 21

quality:
  path: shared/quality.yaml
storage:
  path: shared/storage.yaml
